apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp
spec:
  selector:
    matchLabels:
      app: sa-webapp
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-webapp
    spec:
      containers:
        - image: milantimotijevic89/sentiment-analysis-webapp
          imagePullPolicy: Always
          name: sa-webapp
          env:
            - name: LOGIC_SERVICE
              value: "http://sa-logic"
          ports:
            - containerPort: 8080
